opinion_junkie_proj/opinion_junkie_app/urls.py
from django import views
from django.urls import path
from . import views

app_name = 'opinion_junkie_app'
urlpatterns = [
    path('', views.home, name='myview'),
    path('home/', views.home, name='home'),
    path('detail/<int:movie_id>', views.detail, name='detail'),
    path('reviews/<int:movie_id>', views.reviews, name='reviews'),
    path('favorite/<int:movie_id>', views.favorite, name='favorite')
]

opinion_junkie_proj/opinion_junkie_proj/urls.py
from django.contrib import admin
from django.urls import path, include
from users_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('opinion_junkie_app.urls')),
    path('', include('users_app.urls')),
]

opinion_junkie_proj/users_app/urls.py
from django.urls import path

from . import views

app_name = 'users_app'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('users/<str:username>', views.profile, name='profile')
]

opinion_junkie_proj/opinion_junkie_app/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.core.validators import MaxValueValidator, MinValueValidator

class Movie(models.Model):
    title = models.CharField(max_length=200)
    release_date = models.CharField(max_length=200)
    genre = models.CharField(max_length=200)
    poster_url = models.CharField(max_length=255)


    def __str__(self):
        return f"{self.title}"

class Review(models.Model):
    post = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='reviews')
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, related_name='reviews')
    rating = models.DecimalField(
        default=0.0,
        validators= [
            MaxValueValidator(5.0),
            MinValueValidator(0.0)
        ],
        decimal_places=1,
        max_digits=2
    )

    def __str__(self):
        return f"{self.movie} - {self.pub_date}"

opinion_junkie_proj/users_app/models.py
from django.db import models

from opinion_junkie_app.models import Movie

# Create your models here.
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):

    favorites = models.ManyToManyField(Movie, blank=True, related_name='users')

    def __str__(self):
        return self.username

opinion_junkie_proj/opinion_junkie_app/views.py
from email import contentmanager, message
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from requests import post
from .models import Movie, Review, get_user_model
from django.contrib.auth.decorators import login_required

def home(request):
    movies = Movie.objects.all()
    context = {
        'movies': movies
    }
    return render(request, 'home/index.html', context)

def detail(request, movie_id):
    movie = get_object_or_404(Movie, id=movie_id)

    context = {
        'movie': movie
    }

    return render(request, 'movie/detail.html', context)

def reviews(request, movie_id):

    movie = (Movie, movie_id)

    context = {
        'post': post
    }

    return render(request, 'reviews/reviews.html', context)


@login_required
def favorite(request, movie_id):

    movie = get_object_or_404(Movie, id=movie_id)

    if request.user not in movie.users.all():

        movie.users.add(request.user)

    else:
        pass

    return JsonResponse({
        'Favorited': request.user in movie.users.all(),
    })

opinion_junkie_proj/users_app/views.py
from operator import index
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponse
from django.http import JsonResponse
from .models import Movie



from .models import User
from django.contrib.auth import (
    authenticate, 
    get_user_model,
    login as django_login,
    logout as django_logout
    )

from django.contrib import messages

from django.contrib.auth.decorators import login_required

# Create your views here.
def register(request):

    if request.method == 'GET':
        return render(request, 'register.html')

    elif request.method == 'POST':
        form = request.POST

        username = form.get('username')
        password = form.get('password')

        new_user = User.objects.create_user(
            username=username,
            password=password
        )

        messages.success(request, f'Welcome, {new_user.username}')

        django_login(request, new_user)

        return redirect('opinion_junkie_app:home')

def login(request):

    if request.method == 'GET':
        return render(request, 'login.html')

    elif request.method == 'POST':
        form = request.POST

        username = form.get('username')
        password = form.get('password')

        user = authenticate(request, username=username, password=password)

        if user is None:

            messages.error(request, 'Invalid Username or Password')
            return render(request, 'login.html')

        django_login(request, user)

        messages.success(request, f"Welcome {user.username}!")

        return redirect('opinion_junkie_app:home')


@login_required
def profile(request, username):
    user = get_object_or_404(get_user_model(),username=username)

    return render(request, 'profile.html')

opinion_junkie_proj/opinion_junkie_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.27.2/axios.min.js
    "></script>

    <title>Opinion Junkie</title>
</head>
<body>

    <h1 class="display-5 ctm-h p-5">Opinion Junkie</h1>

<!-- if user is logged in, display logout -->
<!-- move login/logout icon into header -->


    <a class="d-flex justify-content-end" href="{% url 'users_app:login' %}" title="Login">Login<i style="color: #cbb26a;" class="bi bi-door-open"></i></a>


    
        {% if messages %}
            
            {% for message  in messages %}

                {{message}}
                
            {% endfor %}


        {% endif %}


        {% block content %}

        

        {% endblock content %}
    


</body>
</html>

opinion_junkie_proj/opinion_junkie_app/templates/home/index.html
{% extends 'base.html' %}


{% block content %}

{% load static %}



    <section class="container-fluid">

        
        <div class="row">

            <div class="
                    col-12
                    col-lg-2 
                    d-none
                    d-lg-block
                    p-5
                    vh-100
                    card-ctm
                    ">
                    <button class="btn btn-dark button-ctm m-3 border border-4" type="button">About</button>
                    <button class="btn btn-dark button-ctm m-3 border border-4" type="button">Movies</button>
                    <button class="btn btn-dark button-ctm m-3 border border-4" type="button">Books</button>
                    <button class="btn btn-dark button-ctm m-3 border border-4" type="button">TV Shows</button>
                    <button class="btn btn-dark button-ctm m-3 border border-4" type="button">Games</button>
                </div>

                <div class="col-12 col-lg-10 p-5">

                    <div class="row">

                        <div class="
                                col-12 
                                d-flex 
                                flex-column align-items-center
                                flex-lg-row justify-content-lg-center
                            "
                        >
                        
                        <button class="btn btn-dark button-ctm m-3" type="button">All Time</button>
                        <button class="btn btn-dark button-ctm m-3" type="button">By Genre</button>
                        <button class="btn btn-dark button-ctm m-3" type="button">By Release Year</button>

                        </div>

                        <div class="col-12">
                            
                            <div class="row">
                                
                                
                                {% for movie in movies %}
                                <div class="col-12 col-lg-4">
                                    <div class="p-2 mb-2 d-flex justify-content-center">
                                        <!-- <img src='https://picsum.photos/200/300'> -->
                                        <img src="{{ movie.poster_url }}" alt="{{movie.title}}">
                                        
                                        <a href="{% url 'opinion_junkie_app:detail' movie.id %}"<button type="submit" class="btn btn-dark button-ctm m-3 d-flex align-items-center">{{ forloop.counter }}. {{ movie.title }}</button></a>
                                    </div>
                                </div>
                                {% endfor %} 


                            </div>

                        </div>
                        




                        
                </div>

                </div>
            

                

            </div>

        </section>
{% endblock content %}

opinion_junkie_proj/opinion_junkie_app/templates/movie/detail.html
{% extends 'base.html' %}


{% block content %}

{% load static %}


<section class="container-fluid">

    
    <div class="row">
        
        <div class="
        col-12
                col-lg-2 
                d-none
                d-lg-block
                p-5
                vh-100
                card-ctm
                ">
                <a href="{% url 'opinion_junkie_app:home' %}"><button class="btn btn-dark button-ctm m-3 border border-4" type="button">Home</button></a>
                <button class="btn btn-dark button-ctm m-3 border border-4" type="button">Ratings</button>
                
                <button class="btn btn-dark button-ctm m-3 border border-4" type="button">Reviews</button>
                
                {% csrf_token %}
                
                    <button id="fav-btn-{{movie.id}}" class="fav-btn btn btn-dark button-ctm m-3 border border-4" onclick="handleFavEvent(event)"> 
                
                        {% if request.user in movie.users.all %}
                        <i class="fav-btn-icon bi bi-bookmark-heart-fill"></i>
                        {% else %}
                        <i class="fav-btn-icon bi bi-bookmark-heart"></i>
                        {% endif %}
                        Favorite

                    </button>
                
                    <a href="{% url 'opinion_junkie_app:reviews' movie.id %}"><button class="btn btn-dark button-ctm m-3 border border-4" type="button">Add review  <i class="bi bi-chat-right-text"></i></button></a>
            
                </div>
                
            <div class="col-12 col-lg-10 p-5">

                <div class="row">

                    <div class="
                    col-12 
                    d-flex 
                            flex-column align-items-center
                            flex-lg-row justify-content-lg-center
                            d-block
                            d-md-none
                            "
                            >
                    
                        <a href="{% url 'opinion_junkie_app:home' %}"><button class="btn btn-dark button-ctm mb-3 p-3" type="button">Home</button></a>
                        

                        <button id="fav-btn-{{movie.id}}" class="fav-btn btn btn-dark button-ctm mb-3 p-2" onclick="handleFavEvent(event)"> 
                
                            {% if request.user in movie.users.all %}
                            <i class="fav-btn-icon bi bi-bookmark-heart-fill"></i>
                            {% else %}
                            <i class="fav-btn-icon bi bi-bookmark-heart"></i>
                            {% endif %}
                            Favorite
    
                        </button>
                    
                        <a href="{% url 'opinion_junkie_app:reviews' movie.id %}"><button class="btn btn-dark button-ctm mb-3" type="button">Leave a review  <i class="bi bi-chat-right-text"></i></button></a>

                    </div>
                    
                    <div class="col-12">
                        
                        <div class="row border border-4 mb-4 card-ctm rounded">

                            <div class="col-lg-12">
                                <div class="p-4 d-flex justify-content-center">
                                    <h1 class="display-5"> {{ movie.title }}</h1>
                                    
                                </div>
                            </div>

                        </div>
                        
                        <div class="row">
                            
                            <div class="col-12 col-lg-5">
                                <div class="p-2 mb-2 d-flex justify-content-center">
                                    <!-- <img src="https://picsum.photos/300/400" class="rounded"> -->

                                    <img src="{{ movie.poster_url }}" alt="{{movie.title}}">

                                </div>
                                <div class="row mb-4">
                                    <div class="card-ctm-1 d-flex justify-content-center">
                                        Rating
                                    </div>
                                </div>
                            </div>
                            
                            
                            <div class="card-ctm col-12 col-lg-6 rounded">
                                <div class="p-4 d-flex">

                                    Release Date: {{movie.release_date}}</br> </br> </br>
                                    Genre: {{movie.genre}} </br> </br> </br>
                                    <!-- Main Characters: </br> </br> </br>  -->
                                </div>
                            </div>


                        </div>

                        <div class="row">

                            
                            <div class="card-ctm col-12 col-lg-12 mt-5 rounded border border-4 mb-2">

                                <div class="p-4 d-flex">

                                    <h3 class="font-weight-bold ">Reviews:</h3>

                                </div>

                            </div>

                        </div>

                        <div class="row">

                            {% for review in movie.reviews.all %}

                            <div class="card-ctm col-12 col-lg-12 rounded p-3 m-3" >

                                {{review.post}}

                            </div>

                            {% endfor %}
                            
                        </div>


                        


                    </div>
                    

                </div>
                
            </div>
    
            
            
    </div>

</section>
<script src="{% static 'js/index.js' %}"></script>
     
{% endblock content %}

opinion_junkie_proj/opinion_junkie_app/templates/reviews/reviews.html
{% extends 'base.html' %}


{% block content %}

{% load static %}


<form action="{% url 'opinion_junkie_app:detail' movie.id %}" method="POST" class="d-flex justify-conent-end">
                                
    <label for="review">Type here</label>
    <input type="text" name="review" id="review">
    
    <br/>
    
    <input type="submit" id="submit" value="Enter">
    
    {% csrf_token %}
    
</form>

{% endblock content %}

opinion_junkie_proj/users_app/templates/login.html
{% extends 'base.html' %}

{% block content %}

<div class="row">

    <h2 class="col-12
                d-flex
                justify-content-center
                mt-5
                ctm-fnt">
                Login</h2>

    <div class="col-12
                d-flex 
                justify-content-center 
                mt-4
                ctm-fnt
                ">

                <form action="{% url 'users_app:login' %}" method="POST" class="ctm-fnt">

                    <label for="username">Username</label>
                    <input type="text" name="username" id="username">

                    <br/>
                    
                    <label for="password">Password</label>
                    <input type="password" name="password" id="password">

                    <br/>
                    <!-- center Enter button ------------------------------------------------------ -->
                    <input type="submit" id="submit" value="Enter">

                    {% csrf_token %}

                </form>
                
                
            </div>
            
    <div class="row p-5">

        <p class="col-12 d-flex justify-content-center">
            Don't have an account?</p>
        <a href="{% url 'users_app:register' %}" class="col-12 d-flex justify-content-center">Sign Up Here</a>

    </div>

</div>
    


{% endblock content %}

opinion_junkie_proj/users_app/templates/profile.html
{% extends 'base.html' %}

{% block content %}

{{user.username}}

    
{% endblock content %}

opinion_junkie_proj/users_app/templates/register.html
{% extends 'base.html' %}

{% block content %}

<div class="row">

    <h2 class="col-12
                d-flex
                justify-content-center
                mt-5
                ctm-fnt">
                Register</h2>

    <div class="col-12
                d-flex 
                justify-content-center 
                mt-4
                ctm-fnt
                ">

                <form action="{% url 'users_app:register' %}" method="POST" class="ctm-fnt">

                    <label for="username">Username</label>
                    <input type="text" name="username" id="username">

                    <br/>
                    
                    <label for="password">Password</label>
                    <input type="password" name="password" id="password">

                    <br/>

                    <input type="submit" id="submit" value="Submit">

                    {% csrf_token %}

                </form>

    </div>

    <div class="row p-5">

        <p class="col-12 d-flex justify-content-center">
            Already have an account?</p>
        <a href="{% url 'users_app:login' %}" class="col-12 d-flex justify-content-center">Login Here</a>

    </div>

</div>
    


{% endblock content %}